"""
ProcessOS Claude Instruction Pack Generator

Generates dual-mode instruction files for Claude (terminal + VSCode).
"""

import hashlib
import json
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

from process_os.stack_fingerprint import StackFingerprint


SCHEMA_VERSION = "1.0.0"


@dataclass
class InstructionPackConfig:
    """Configuration for instruction pack generation."""

    project_name: str
    host_root: Path
    fingerprint: StackFingerprint
    binding_id: str
    processos_root: str = ".processos"
    tools_enabled: bool = False
    auto_apply_patchsets: bool = False
    gate_policy: str = "halt_on_failure"


class InstructionPackGenerator:
    """
    Generates Claude instruction pack files.

    All outputs are deterministic for the same input configuration.
    """

    def __init__(self, config: InstructionPackConfig):
        self.config = config
        self.timestamp: Optional[str] = None  # For deterministic testing

    def set_timestamp(self, timestamp: str) -> None:
        """Set fixed timestamp for deterministic output."""
        self.timestamp = timestamp

    def generate(self, output_dir: Path) -> List[Path]:
        """
        Generate all instruction pack files.

        Args:
            output_dir: Directory to write files (usually .processos/claude/)

        Returns:
            List of generated file paths
        """
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)

        files = []

        # Generate each file
        files.append(self._write_instructions(output_dir))
        files.append(self._write_contracts(output_dir))
        files.append(self._write_entrypoint(output_dir))
        files.append(self._write_context(output_dir))

        return files

    def _get_timestamp(self) -> str:
        """Get timestamp (fixed or current)."""
        return self.timestamp or datetime.now(timezone.utc).isoformat()

    def _get_stack_summary(self) -> str:
        """Get human-readable stack summary."""
        stacks = self.config.fingerprint.get_stack_ids()
        if not stacks:
            return "unknown technology"
        return " + ".join(stacks)

    def _get_stack_details(self) -> str:
        """Get detailed stack information."""
        lines = []
        for stack in self.config.fingerprint.stacks:
            line = f"- **{stack['stack_id']}** ({stack['confidence']} confidence)"
            if stack.get("version_hint"):
                line += f" - Version: {stack['version_hint']}"
            lines.append(line)

        for fw in self.config.fingerprint.frameworks:
            lines.append(f"- Framework: **{fw['framework_id']}** ({fw['stack']})")

        return "\n".join(lines) if lines else "- No specific stack detected"

    def _write_instructions(self, output_dir: Path) -> Path:
        """Generate INSTRUCTIONS.md."""
        content = f"""# Claude Instructions for {self.config.project_name}

## Your Role

You are assisting with **{self.config.project_name}**, a {self._get_stack_summary()} project.

ProcessOS is managing this project to ensure deterministic, auditable AI assistance.

## Rules

1. **NEVER** modify files outside `.processos/` without explicit user approval
2. **ALWAYS** use `processos cmd` for task execution when available
3. **HALT** immediately if you detect drift from approved contracts
4. **LOG** all significant actions for auditability

## Available Commands

```bash
# Execute a task
processos cmd "<task description>" --host {self.config.host_root}

# Check project status
processos status --host {self.config.host_root}

# Refresh stack detection
processos fingerprint --host {self.config.host_root}
```

## Stack Context

{self._get_stack_details()}

## Working Directory

- Host project: `{self.config.host_root}`
- ProcessOS data: `{self.config.host_root}/{self.config.processos_root}/`
- Run outputs: `{self.config.host_root}/{self.config.processos_root}/runs/`

## Patchset Workflow

If you need to modify host code:
1. Generate a patchset using ProcessOS
2. Output the patchset to `.processos/patchsets/`
3. **NEVER** auto-apply - user must review and apply manually

---

*Generated by ProcessOS - {self._get_timestamp()}*
"""
        path = output_dir / "INSTRUCTIONS.md"
        path.write_text(content, encoding="utf-8")
        return path

    def _write_contracts(self, output_dir: Path) -> Path:
        """Generate CONTRACTS.md."""
        content = f"""# Non-Negotiable Contracts

These contracts are enforced by ProcessOS drift guards. Violations will halt execution.

## Write Allowlist

**ONLY** these paths may be written:

```
.processos/**
```

Any attempt to write outside this allowlist will:
- Raise a `DriftViolationError`
- Emit a `drift_detected` event
- Halt execution immediately

## Forbidden Actions

| Action | Consequence |
|--------|-------------|
| Modify host source code directly | HALT |
| Bypass gates | HALT |
| Skip telemetry | HALT |
| Auto-apply patchsets | HALT |
| Make network calls during bootstrap | HALT |

## Gate Policy

- Gate failure = **HALT**
- No alternate execution paths allowed
- No retries without user intervention
- All violations logged with deterministic reason

## Telemetry Chain

Every execution **MUST** preserve the trace chain:

```
command_id → workspace_id → run_id
```

This chain must be:
- Verifiable in `.processos/runs/<run_id>/telemetry.jsonl`
- Consistent across all generated files
- Deterministic (same input = same IDs)

## Determinism Guarantee

For the same host state and command:
- Same `command_id`
- Same `workspace_id`
- Same file hashes
- Byte-identical outputs

## Policy Settings

| Policy | Value |
|--------|-------|
| Tools enabled | {str(self.config.tools_enabled).lower()} |
| Auto-apply patchsets | {str(self.config.auto_apply_patchsets).lower()} |
| Gate policy | {self.config.gate_policy} |

---

*Generated by ProcessOS - {self._get_timestamp()}*
"""
        path = output_dir / "CONTRACTS.md"
        path.write_text(content, encoding="utf-8")
        return path

    def _write_entrypoint(self, output_dir: Path) -> Path:
        """Generate ENTRYPOINT_PROMPT.txt."""
        stack_ids = ", ".join(self.config.fingerprint.get_stack_ids()) or "unknown"

        content = f"""You are Claude, assisting with {self.config.project_name}.

CRITICAL: Before ANY action, read these files:
- {self.config.processos_root}/claude/INSTRUCTIONS.md
- {self.config.processos_root}/claude/CONTRACTS.md
- {self.config.processos_root}/claude/PROJECT_CONTEXT.json

Execute tasks ONLY via:
  processos cmd "<task>" --host {self.config.host_root}

Current stack: {stack_ids}
Fingerprint: {self.config.fingerprint.fingerprint_id}
Binding: {self.config.binding_id}

What would you like me to help with?
"""
        path = output_dir / "ENTRYPOINT_PROMPT.txt"
        path.write_text(content, encoding="utf-8")
        return path

    def _write_context(self, output_dir: Path) -> Path:
        """Generate PROJECT_CONTEXT.json."""
        context = {
            "schema_version": SCHEMA_VERSION,
            "fingerprint_id": self.config.fingerprint.fingerprint_id,
            "binding_id": self.config.binding_id,
            "host_root": str(self.config.host_root),
            "processos_root": self.config.processos_root,
            "generated_at": self._get_timestamp(),
            "stacks": self.config.fingerprint.stacks,
            "frameworks": self.config.fingerprint.frameworks,
            "policies": {
                "write_allowlist": [".processos/**"],
                "tools_enabled": self.config.tools_enabled,
                "auto_apply_patchsets": self.config.auto_apply_patchsets,
                "gate_policy": self.config.gate_policy,
            },
            "commands": {
                "execute": f'processos cmd "<task>" --host {self.config.host_root}',
                "status": f"processos status --host {self.config.host_root}",
                "fingerprint": f"processos fingerprint --host {self.config.host_root}",
            },
        }

        # Deterministic JSON output
        content = json.dumps(context, indent=2, sort_keys=True, ensure_ascii=False)

        path = output_dir / "PROJECT_CONTEXT.json"
        path.write_text(content, encoding="utf-8")
        return path


def generate_instruction_pack(
    config: InstructionPackConfig,
    output_dir: Path,
    timestamp: Optional[str] = None,
) -> List[Path]:
    """
    Convenience function to generate instruction pack.

    Args:
        config: Pack configuration
        output_dir: Output directory
        timestamp: Optional fixed timestamp

    Returns:
        List of generated file paths
    """
    generator = InstructionPackGenerator(config)
    if timestamp:
        generator.set_timestamp(timestamp)
    return generator.generate(output_dir)
