"""
Architecture analyzer for ProcessOS.

Main entry point for architecture detection, analysis, and reporting.
Orchestrates language/framework detection, pattern discovery, and convention learning.
"""

from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Optional, List, Dict

from process_os.architecture.types import ProjectArchitecture, ProgrammingLanguage
from process_os.architecture.detector import LanguageDetector, FrameworkDetector
from process_os.patterns import IntegrationPattern, PatternDiscoverer
from process_os.conventions import ConventionLearner, CodeConventions


@dataclass
class ArchitectureReport:
    """Report of project architecture analysis.

    Generated by ArchitectureAnalyzer with language, framework, patterns,
    conventions, recommendations, warnings, and user approval status.
    """

    architecture: ProjectArchitecture
    patterns: List[IntegrationPattern] = field(default_factory=list)
    conventions: Optional[CodeConventions] = None
    recommendations: List[str] = field(default_factory=list)
    warnings: List[str] = field(default_factory=list)
    analyzed_at: datetime = field(default_factory=datetime.now)
    user_approved: bool = False
    approved_at: Optional[datetime] = None
    user_corrections: Dict = field(default_factory=dict)

    def apply_user_approval(self) -> None:
        """Mark architecture as approved by user."""
        self.user_approved = True
        self.approved_at = datetime.now()

    def apply_corrections(self, corrections: Dict) -> None:
        """Apply user corrections to architecture and recalculate confidence."""
        self.user_corrections = corrections

        # Apply language correction if provided
        if "language" in corrections:
            self.architecture.language = corrections["language"]

        # Apply framework correction if provided
        if "framework" in corrections:
            self.architecture.framework = corrections["framework"]

        # Apply project type correction if provided
        if "project_type" in corrections:
            self.architecture.project_type = corrections["project_type"]

        # Penalty for user overrides: reduce confidence by 15%
        self.architecture.confidence = max(0.5, self.architecture.confidence - 0.15)


class ArchitectureAnalyzer:
    """Main analyzer for project architecture detection and reporting.

    Orchestrates:
    1. Language detection
    2. Framework detection
    3. Pattern discovery
    4. Convention learning
    5. Recommendations and warnings generation
    """

    def __init__(self):
        """Initialize the architecture analyzer."""
        self.language_detector = LanguageDetector()
        self.framework_detector = FrameworkDetector()
        self.pattern_discoverer = PatternDiscoverer()
        self.convention_learner = ConventionLearner()

    def analyze(
        self,
        project_path: Path,
        target_directory: Optional[Path] = None,
    ) -> ProjectArchitecture:
        """Analyze project and return detected architecture.

        Args:
            project_path: Path to project root
            target_directory: Optional subdirectory for monorepos

        Returns:
            ProjectArchitecture with confidence >= 0.9

        Raises:
            ValueError: If detection confidence is below 0.9
        """
        if not isinstance(project_path, Path):
            project_path = Path(project_path)

        # Detect language
        language_detection = self.language_detector.detect(
            project_path,
            target_directory,
        )

        # Detect framework
        framework_detection = self.framework_detector.detect(
            project_path,
            language_detection.detected_language,
            target_directory,
        )

        # Create architecture with detected values
        architecture = ProjectArchitecture(
            root_path=target_directory or project_path,
            language=language_detection.detected_language,
            framework=framework_detection.detected_framework,
            confidence=min(
                language_detection.confidence,
                framework_detection.confidence,
            ),
            detection_signals=[language_detection, framework_detection],
            project_type=framework_detection.project_type,
            target_directory=target_directory,
        )

        # Validate confidence threshold
        if architecture.confidence < 0.9:
            raise ValueError(
                f"Architecture detection confidence {architecture.confidence:.2%} "
                f"is below required threshold 0.9. "
                f"Use user corrections to override or provide more context."
            )

        return architecture

    def generate_report(
        self,
        architecture: ProjectArchitecture,
        discover_patterns: bool = True,
        learn_conventions: bool = True,
    ) -> ArchitectureReport:
        """Generate comprehensive architecture analysis report.

        Args:
            architecture: Detected project architecture
            discover_patterns: Whether to discover integration patterns
            learn_conventions: Whether to learn code conventions

        Returns:
            ArchitectureReport with analysis and recommendations
        """
        patterns = []
        conventions = None

        # Discover patterns if requested
        if discover_patterns and architecture.root_path.exists():
            try:
                discovered_patterns = self.pattern_discoverer.discover_all(
                    architecture.root_path,
                    architecture.language,
                )
                patterns = discovered_patterns
            except Exception:
                # Silently continue if pattern discovery fails
                pass

        # Learn conventions if requested
        if learn_conventions and architecture.root_path.exists():
            try:
                conventions = self.convention_learner.learn_conventions(
                    architecture.root_path,
                    architecture,
                    sample_size=10,
                )
            except Exception:
                # Silently continue if convention learning fails
                pass

        # Generate recommendations
        recommendations = self._generate_recommendations(
            architecture,
            patterns,
            conventions,
        )

        # Generate warnings
        warnings = self._generate_warnings(
            architecture,
            patterns,
            conventions,
        )

        return ArchitectureReport(
            architecture=architecture,
            patterns=patterns,
            conventions=conventions,
            recommendations=recommendations,
            warnings=warnings,
            analyzed_at=datetime.now(),
        )

    def _generate_recommendations(
        self,
        architecture: ProjectArchitecture,
        patterns: List[IntegrationPattern],
        conventions: Optional[CodeConventions],
    ) -> List[str]:
        """Generate recommendations based on analysis."""
        recommendations = []

        # Framework-specific recommendations
        if architecture.framework:
            if architecture.framework.value == "laravel":
                recommendations.extend([
                    "Use Adapter pattern for external service integration",
                    "Register adapters in Laravel ServiceProvider",
                    "Follow App\\Services\\{Domain} naming convention",
                    "Use dependency injection via service container",
                ])
            elif architecture.framework.value == "django":
                recommendations.extend([
                    "Use service classes in services.py",
                    "Register services in Django apps.py",
                    "Follow app_name/services.py directory structure",
                ])

        # Pattern-based recommendations
        if patterns:
            recommendations.append(
                f"Discovered {len(patterns)} integration patterns - analyze for reuse"
            )

        # Convention-based recommendations
        if conventions and conventions.namespace_pattern:
            recommendations.append(
                f"Follow namespace pattern: {conventions.namespace_pattern}"
            )

        return recommendations

    def _generate_warnings(
        self,
        architecture: ProjectArchitecture,
        patterns: List[IntegrationPattern],
        conventions: Optional[CodeConventions],
    ) -> List[str]:
        """Generate warnings for potential issues."""
        warnings = []

        # Confidence-related warnings
        if architecture.confidence < 0.95:
            warnings.append(
                f"Detection confidence {architecture.confidence:.0%} is below ideal threshold 0.95 - "
                f"code generation may be less accurate"
            )

        # Monorepo-related warnings
        if architecture.project_type.value == "monorepo" and not architecture.target_directory:
            warnings.append(
                "Monorepo structure detected - use --target-dir to specify which subdirectory to analyze"
            )

        # Pattern consistency warnings
        if conventions and hasattr(conventions, "confidence"):
            if conventions.confidence < 0.7:  # type: ignore
                warnings.append(
                    "Convention learning confidence is low - detected patterns may be inconsistent"
                )

        return warnings
