"""
ProcessOS Code Generator Module

Generates integration code tailored to project conventions.
"""

import difflib
import re
import uuid
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, Optional, TYPE_CHECKING

from .types import (
    FileType,
    GeneratedCode,
    GeneratedFile,
)

if TYPE_CHECKING:
    from ..discovery import ProjectContext, ProjectConventions
    from ..intent import Intent
    from ..mapping import SchemaMapping
    from ..requirements import MaterialCollection


# Python code templates
PYTHON_SERVICE_TEMPLATE = '''"""
{service_name} - Integration Service

Generated by ProcessOS Dynamic Integration Engine.
"""

import os
import requests
from typing import Any, Dict, List, Optional


class {class_name}:
    """
    {description}
    """

    def __init__(self, base_url: str = None, api_key_env: str = "{api_key_env}"):
        """
        Initialize the service.

        Args:
            base_url: API base URL (defaults to {default_base_url})
            api_key_env: Environment variable name for API key
        """
        self.base_url = base_url or "{default_base_url}"
        self.api_key = os.environ.get(api_key_env)

    def _make_request(
        self,
        method: str,
        endpoint: str,
        data: Optional[Dict] = None,
        params: Optional[Dict] = None,
    ) -> Dict[str, Any]:
        """Make an API request."""
        url = f"{{self.base_url}}{{endpoint}}"
        headers = {{"Authorization": f"Bearer {{self.api_key}}"}}

        response = requests.request(
            method=method,
            url=url,
            json=data,
            params=params,
            headers=headers,
        )
        response.raise_for_status()
        return response.json()

{methods}
'''

PYTHON_METHOD_TEMPLATE = '''    def {method_name}(self{params}) -> {return_type}:
        """
        {description}
{param_docs}
        Returns:
            {return_desc}
        """
        return self._make_request("{http_method}", "{endpoint}"{request_args})
'''

PYTHON_MODEL_TEMPLATE = '''"""
{model_name} - Data Model

Generated by ProcessOS Dynamic Integration Engine.
"""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Dict, List, Optional


@dataclass
class {class_name}:
    """
    {description}
    """

{fields}

    def to_dict(self) -> Dict[str, Any]:
        """Serialize to dictionary."""
        return {{
{to_dict_fields}
        }}

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "{class_name}":
        """Deserialize from dictionary."""
        return cls(
{from_dict_fields}
        )
'''

# JavaScript/Node templates
JS_SERVICE_TEMPLATE = '''/**
 * {service_name} - Integration Service
 *
 * Generated by ProcessOS Dynamic Integration Engine.
 */

const axios = require('axios');

class {class_name} {{
    constructor(baseUrl = '{default_base_url}', apiKeyEnv = '{api_key_env}') {{
        this.baseUrl = baseUrl;
        this.apiKey = process.env[apiKeyEnv];
    }}

    async _makeRequest(method, endpoint, data = null, params = null) {{
        const url = `${{this.baseUrl}}${{endpoint}}`;
        const response = await axios({{
            method,
            url,
            data,
            params,
            headers: {{ 'Authorization': `Bearer ${{this.apiKey}}` }}
        }});
        return response.data;
    }}

{methods}
}}

module.exports = {class_name};
'''


class CodeGenerator:
    """
    Generates integration code tailored to project conventions.

    Supports:
    - Python (Django, Flask, FastAPI)
    - JavaScript/TypeScript (Express, Node)
    """

    def __init__(self, project_context: Optional["ProjectContext"] = None):
        """
        Initialize the CodeGenerator.

        Args:
            project_context: Project context with conventions
        """
        self.project_context = project_context

    def generate(
        self,
        intent: "Intent",
        mapping: "SchemaMapping",
        materials: "MaterialCollection",
    ) -> GeneratedCode:
        """
        Generate integration code.

        Args:
            intent: Parsed user intent
            mapping: Schema mappings
            materials: Collected materials

        Returns:
            GeneratedCode with generated files
        """
        generated = GeneratedCode(
            playbook_id=getattr(intent, "id", None) or intent.integration_type,
            mapping_id=getattr(mapping, "id", None) or getattr(mapping, "intent_id", "unknown"),
            generated_at=datetime.now(),
        )

        # Generate service file
        service_info = self._build_service_info(intent, mapping, materials)
        service_code = self.generate_service(service_info)
        generated.add_file(
            GeneratedFile(
                id=f"gf-{uuid.uuid4().hex[:8]}",
                file_path=self._get_service_path(service_info["name"]),
                file_type=FileType.SERVICE,
                content=service_code,
            )
        )

        # Generate model file if needed
        if mapping.field_mappings:
            model_info = self._build_model_info(mapping)
            model_code = self.generate_model(model_info)
            generated.add_file(
                GeneratedFile(
                    id=f"gf-{uuid.uuid4().hex[:8]}",
                    file_path=self._get_model_path(model_info["name"]),
                    file_type=FileType.MODEL,
                    content=model_code,
                )
            )

        return generated

    def generate_service(self, service_info: Dict[str, Any]) -> str:
        """
        Generate service class code.

        Args:
            service_info: Service specification

        Returns:
            Generated service code
        """
        language = self._get_language()

        if language in ("python", ""):
            return self._generate_python_service(service_info)
        elif language in ("javascript", "typescript"):
            return self._generate_js_service(service_info)
        else:
            return self._generate_python_service(service_info)

    def generate_model(self, model_info: Dict[str, Any]) -> str:
        """
        Generate model/dataclass code.

        Args:
            model_info: Model specification

        Returns:
            Generated model code
        """
        class_name = self._format_class_name(model_info["name"])
        fields = model_info.get("fields", [])

        field_lines = []
        to_dict_lines = []
        from_dict_lines = []

        for f in fields:
            field_name = self._format_field_name(f["name"])
            field_type = self._map_type_to_python(f.get("type", "string"))
            nullable = f.get("nullable", True)

            if nullable:
                field_lines.append(f"    {field_name}: Optional[{field_type}] = None")
            else:
                field_lines.append(f"    {field_name}: {field_type}")

            to_dict_lines.append(f'            "{f["name"]}": self.{field_name},')
            from_dict_lines.append(f'            {field_name}=data.get("{f["name"]}"),')

        return PYTHON_MODEL_TEMPLATE.format(
            model_name=model_info["name"],
            class_name=class_name,
            description=model_info.get("description", f"Data model for {model_info['name']}"),
            fields="\n".join(field_lines) or "    pass",
            to_dict_fields="\n".join(to_dict_lines),
            from_dict_fields="\n".join(from_dict_lines),
        )

    def generate_controller(self, controller_info: Dict[str, Any]) -> str:
        """
        Generate controller/route handler code.

        Args:
            controller_info: Controller specification

        Returns:
            Generated controller code
        """
        # Placeholder for controller generation
        return f"# Controller for {controller_info.get('name', 'unknown')}\n"

    def generate_tests(self, test_info: Dict[str, Any]) -> str:
        """
        Generate test code.

        Args:
            test_info: Test specification

        Returns:
            Generated test code
        """
        class_name = test_info.get("class_name", "TestIntegration")
        service_name = test_info.get("service_name", "Service")

        return f'''"""Tests for {service_name}."""

import pytest
from unittest.mock import Mock, patch


class {class_name}:
    """Test suite for {service_name}."""

    def test_initialization(self):
        """Test service initialization."""
        # TODO: Implement test
        pass

    def test_api_call(self):
        """Test API call."""
        # TODO: Implement test
        pass
'''

    def preview_diff(self, file: GeneratedFile) -> str:
        """
        Generate diff preview for a file.

        Args:
            file: GeneratedFile to preview

        Returns:
            Unified diff string
        """
        return self.generate_diff(
            original=file.original_content,
            modified=file.content,
            file_path=str(file.file_path),
        )

    @staticmethod
    def generate_diff(
        original: Optional[str],
        modified: str,
        file_path: str,
    ) -> str:
        """
        Generate unified diff between original and modified content.

        Args:
            original: Original content (None for new files)
            modified: Modified/new content
            file_path: File path for diff header

        Returns:
            Unified diff string
        """
        if original is None:
            # New file - show all lines as additions
            lines = [
                "--- /dev/null",
                f"+++ b/{file_path}",
                "@@ -0,0 +1 @@",
            ]
            for line in modified.splitlines():
                lines.append(f"+{line}")
            return "\n".join(lines)

        original_lines = original.splitlines(keepends=True)
        modified_lines = modified.splitlines(keepends=True)

        diff = difflib.unified_diff(
            original_lines,
            modified_lines,
            fromfile=f"a/{file_path}",
            tofile=f"b/{file_path}",
        )

        return "".join(diff)

    def _generate_python_service(self, service_info: Dict[str, Any]) -> str:
        """Generate Python service code."""
        class_name = self._format_class_name(service_info["name"])
        methods_code = []

        for method in service_info.get("methods", []):
            method_name = self._format_method_name(method["name"])
            params = method.get("params", [])
            param_str = ", ".join(f"{p['name']}: {self._map_type_to_python(p.get('type', 'Any'))}" for p in params)
            if param_str:
                param_str = ", " + param_str

            param_docs = ""
            for p in params:
                param_docs += f"            {p['name']}: {p.get('description', 'Parameter')}\n"

            request_args = ""
            if method.get("http_method", "GET").upper() in ("POST", "PUT", "PATCH"):
                request_args = ", data=data"
            elif params:
                request_args = ", params=params"

            methods_code.append(PYTHON_METHOD_TEMPLATE.format(
                method_name=method_name,
                params=param_str,
                return_type=method.get("return_type", "Dict[str, Any]"),
                description=method.get("description", f"Execute {method_name}"),
                param_docs=param_docs if param_docs else "        ",
                return_desc=method.get("return_desc", "API response data"),
                http_method=method.get("http_method", "GET"),
                endpoint=method.get("endpoint", "/"),
                request_args=request_args,
            ))

        return PYTHON_SERVICE_TEMPLATE.format(
            service_name=service_info["name"],
            class_name=class_name,
            description=service_info.get("description", f"Integration service for {service_info['name']}"),
            api_key_env=service_info.get("api_key_env", "API_KEY"),
            default_base_url=service_info.get("base_url", "https://api.example.com"),
            methods="\n".join(methods_code),
        )

    def _generate_js_service(self, service_info: Dict[str, Any]) -> str:
        """Generate JavaScript service code."""
        class_name = self._format_class_name(service_info["name"])
        methods_code = []

        for method in service_info.get("methods", []):
            method_name = self._format_method_name(method["name"])
            methods_code.append(f'''    async {method_name}() {{
        return this._makeRequest('{method.get("http_method", "GET")}', '{method.get("endpoint", "/")}');
    }}
''')

        return JS_SERVICE_TEMPLATE.format(
            service_name=service_info["name"],
            class_name=class_name,
            api_key_env=service_info.get("api_key_env", "API_KEY"),
            default_base_url=service_info.get("base_url", "https://api.example.com"),
            methods="\n".join(methods_code),
        )

    def _build_service_info(
        self,
        intent: "Intent",
        mapping: "SchemaMapping",
        materials: "MaterialCollection",
    ) -> Dict[str, Any]:
        """Build service info from intent and materials."""
        service_name = f"{intent.target_service or 'External'}IntegrationService"

        methods = []
        # Safely get api_docs, handling Mock objects or None
        api_docs = getattr(materials, "api_docs", None)
        if api_docs and hasattr(api_docs, '__iter__') and not isinstance(api_docs, str):
            try:
                for api_doc in api_docs:
                    endpoints = getattr(api_doc, "endpoints", None)
                    if endpoints and hasattr(endpoints, '__iter__') and not isinstance(endpoints, str):
                        try:
                            for endpoint in endpoints:
                                method_name = self._endpoint_to_method_name(endpoint.method, endpoint.path)
                                params = getattr(endpoint, "parameters", [])
                                if not hasattr(params, '__iter__') or isinstance(params, str):
                                    params = []
                                methods.append({
                                    "name": method_name,
                                    "description": getattr(endpoint, "summary", None) or f"{endpoint.method} {endpoint.path}",
                                    "http_method": endpoint.method,
                                    "endpoint": endpoint.path,
                                    "params": [
                                        {"name": p.name, "type": getattr(p, "param_type", "string"), "description": getattr(p, "description", "") or ""}
                                        for p in params
                                    ],
                                })
                        except TypeError:
                            pass  # Handle non-iterable endpoints
            except TypeError:
                pass  # Handle non-iterable api_docs

        api_key_env = "API_KEY"
        base_url = "https://api.example.com"

        # Safely get credential_refs
        cred_refs = getattr(materials, "credential_refs", None)
        if cred_refs and hasattr(cred_refs, '__iter__') and not isinstance(cred_refs, str):
            try:
                for cred in cred_refs:
                    cred_type = getattr(cred, "credential_type", "")
                    if cred_type and "key" in str(cred_type).lower():
                        api_key_env = getattr(cred, "env_var_name", "API_KEY")
                        break
            except TypeError:
                pass

        # Safely get base_url from api_docs
        if api_docs and hasattr(api_docs, '__iter__') and not isinstance(api_docs, str):
            try:
                for api_doc in api_docs:
                    doc_base_url = getattr(api_doc, "base_url", None)
                    if doc_base_url:
                        base_url = doc_base_url
                        break
            except TypeError:
                pass

        return {
            "name": service_name,
            "description": f"Integration service for {intent.target_service or 'external API'}",
            "methods": methods,
            "api_key_env": api_key_env,
            "base_url": base_url,
        }

    def _build_model_info(self, mapping: "SchemaMapping") -> Dict[str, Any]:
        """Build model info from schema mapping."""
        fields = []
        model_name = "IntegrationData"

        # Try field_mappings first, then approved_mappings as fallback
        field_mappings = getattr(mapping, "field_mappings", None)
        if not field_mappings or not hasattr(field_mappings, '__iter__') or isinstance(field_mappings, str):
            field_mappings = getattr(mapping, "approved_mappings", None)

        if field_mappings and hasattr(field_mappings, '__iter__') and not isinstance(field_mappings, str):
            try:
                for fm in field_mappings:
                    # Get field name from local_field or external_field_path
                    field_name = getattr(fm, "local_field", None)
                    if not field_name or not isinstance(field_name, str):
                        external_path = getattr(fm, "external_field_path", "field")
                        field_name = external_path.split(".")[-1] if isinstance(external_path, str) else "field"

                    # Get field type from local_type or external_type
                    field_type = getattr(fm, "local_type", None)
                    if not field_type or not isinstance(field_type, str):
                        field_type = getattr(fm, "external_type", "string")
                        field_type = field_type if isinstance(field_type, str) else "string"

                    fields.append({
                        "name": field_name,
                        "type": field_type,
                        "nullable": True,
                    })

                    # Extract model name from first mapping's local_model
                    if model_name == "IntegrationData":
                        local_model = getattr(fm, "local_model", None)
                        if local_model and isinstance(local_model, str):
                            model_name = local_model
            except TypeError:
                pass  # Handle non-iterable field_mappings

        return {
            "name": model_name,
            "description": f"Data model for {model_name}",
            "fields": fields,
        }

    def _endpoint_to_method_name(self, method: str, path: str) -> str:
        """Convert endpoint to method name."""
        # /customers/{id} GET -> get_customer
        # /orders POST -> create_order
        method_lower = method.lower()
        path_parts = [p for p in path.split("/") if p and not p.startswith("{")]

        if not path_parts:
            return f"{method_lower}_root"

        resource = path_parts[-1]
        # Singularize if it ends with 's'
        if resource.endswith("s") and len(resource) > 1:
            resource = resource[:-1]

        if method_lower == "get" and "{" not in path:
            return f"list_{path_parts[-1]}"
        elif method_lower == "get":
            return f"get_{resource}"
        elif method_lower == "post":
            return f"create_{resource}"
        elif method_lower == "put" or method_lower == "patch":
            return f"update_{resource}"
        elif method_lower == "delete":
            return f"delete_{resource}"

        return f"{method_lower}_{resource}"

    def _format_method_name(self, name: str) -> str:
        """Format method name according to conventions."""
        conventions = self._get_conventions()

        # Handle both object and dict conventions
        if conventions:
            if hasattr(conventions, "function_naming"):
                naming = conventions.function_naming
            elif isinstance(conventions, dict):
                naming = conventions.get("function_naming", "snake_case")
            else:
                naming = "snake_case"
        else:
            naming = "snake_case"

        # Clean the name
        name = re.sub(r'[^\w\s]', '', name)
        words = name.lower().split()

        if naming == "camelCase":
            return words[0] + "".join(w.capitalize() for w in words[1:])
        else:  # snake_case
            return "_".join(words)

    def _format_class_name(self, name: str) -> str:
        """Format class name (always PascalCase)."""
        # Clean the name
        name = re.sub(r'[^\w\s]', '', name)

        # Check if already PascalCase (no spaces and starts with uppercase)
        if ' ' not in name and name[0:1].isupper():
            # Split on uppercase letters to handle "ExternalProduct" -> ["External", "Product"]
            words = re.findall(r'[A-Z][a-z]*|[a-z]+', name)
            if words:
                return "".join(w.capitalize() for w in words)

        # Handle space-separated words
        words = name.split()
        return "".join(w.capitalize() for w in words)

    def _format_field_name(self, name: str) -> str:
        """Format field name according to conventions."""
        return self._format_method_name(name)

    def _get_language(self) -> str:
        """Get project language."""
        if self.project_context:
            if hasattr(self.project_context, "language"):
                return self.project_context.language
            elif isinstance(self.project_context, dict):
                return self.project_context.get("language", "python")
        return "python"

    def _get_conventions(self) -> Optional["ProjectConventions"]:
        """Get project conventions."""
        if self.project_context:
            if hasattr(self.project_context, "conventions"):
                return self.project_context.conventions
            elif isinstance(self.project_context, dict):
                return self.project_context.get("conventions")
        return None

    def _get_service_path(self, service_name: str) -> Path:
        """Get path for service file."""
        language = self._get_language()
        name = self._format_method_name(service_name)

        if language in ("javascript", "typescript"):
            ext = ".ts" if language == "typescript" else ".js"
            return Path(f"services/{name}{ext}")
        else:
            return Path(f"services/{name}.py")

    def _get_model_path(self, model_name: str) -> Path:
        """Get path for model file."""
        language = self._get_language()
        name = self._format_method_name(model_name)

        if language in ("javascript", "typescript"):
            ext = ".ts" if language == "typescript" else ".js"
            return Path(f"models/{name}{ext}")
        else:
            return Path(f"models/{name}.py")

    def _map_type_to_python(self, api_type: str) -> str:
        """Map API type to Python type."""
        type_map = {
            "string": "str",
            "integer": "int",
            "number": "float",
            "boolean": "bool",
            "array": "List",
            "object": "Dict[str, Any]",
        }
        return type_map.get(api_type.lower(), "Any")
